# Sklearn

In [1]:
#Importing pandas and loading data
import pandas as pd
df = pd.read_csv('auto_mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [3]:
#Dropping null values
df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64
 7   origin        392 non-null    object
 8   name          392 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 30.6+ KB

In [4]:
#Creating matrix of predictors
X = df.iloc[:, 1:8]
#Setting target
y = df.iloc[:, 0]
print(X)
print(y)

     cylinders  displacement  horsepower  weight  acceleration  model_year  \
0            8         307.0       130.0    3504          12.0          70
1            8         350.0       165.0    3693          11.5          70
2            8         318.0       150.0    3436          11.0          70
3            8         304.0       150.0    3433          12.0          70
4            8         302.0       140.0    3449          10.5          70
..         ...           ...         ...     ...           ...         ...
393          4         140.0        86.0    2790          15.6          82
394          4          97.0        52.0    2130          24.6          82
395          4         135.0        84.0    2295          11.6          82
396          4         120.0        79.0    2625          18.6          82
397          4         119.0        82.0    2720          19.4          82

     origin
0       usa
1       usa
2       usa
3       usa
4       usa
..      ...
393     usa
394  europe
395     usa
396     usa
397     usa

[392 rows x 7 columns]
0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64

In [5]:
X = pd.get_dummies(X)
X

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_europe,origin_japan,origin_usa
0,8,307.0,130.0,3504,12.0,70,0,0,1
1,8,350.0,165.0,3693,11.5,70,0,0,1
2,8,318.0,150.0,3436,11.0,70,0,0,1
3,8,304.0,150.0,3433,12.0,70,0,0,1
4,8,302.0,140.0,3449,10.5,70,0,0,1
...,...,...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,0,0,1
394,4,97.0,52.0,2130,24.6,82,1,0,0
395,4,135.0,84.0,2295,11.6,82,0,0,1
396,4,120.0,79.0,2625,18.6,82,0,0,1
397,4,119.0,82.0,2720,19.4,82,0,0,1

In [6]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((313, 9), (79, 9), (313,), (79,))

In [7]:
#Applying standard scaler on the data
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train=scale.fit_transform(X_train)
X_test=scale.transform(X_test);
print(X_train)
print(X_test)

[[-0.8576193  -1.04611368 -0.8984236  ... -0.45149325  1.95330095
  -1.28551249]
 [ 0.32752348  0.31263257 -0.1059203  ... -0.45149325 -0.51195388
   0.77789987]
 [-0.8576193  -0.85200708 -0.8984236  ... -0.45149325 -0.51195388
   0.77789987]
 ...
 [-0.8576193  -0.74524844 -0.76633972 ...  2.21487254 -0.51195388
  -1.28551249]
 [ 0.32752348  0.55526583 -0.42292162 ... -0.45149325 -0.51195388
   0.77789987]
 [ 0.32752348 -0.21145527 -0.18517063 ... -0.45149325 -0.51195388
   0.77789987]]
[[-0.8576193  -0.99758703 -0.76633972 -1.00888958 -0.38129265 -0.56648854
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.51232051 -0.42292162 -0.09794779  0.62553132  0.80165122
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.52579886  1.47908629  1.76680366 -0.74087264 -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.85200708 -1.08334104 -1.00888958 -0.30937665  1.62253508
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.92964972 -0.97767393 -0.98507411  0.87723732  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [ 0.32752348  0.38056988 -0.37008807  0.28309976  0.58957333  0.52802327
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -1.00729236 -1.16259137 -1.19584104  1.16490131  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.45408853 -0.97767393  0.33073071  2.24364128  1.07527918
   2.21487254 -0.51195388 -1.28551249]
 [ 0.32752348  0.05058865 -0.23800419  0.15449622  0.33786733 -0.56648854
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.92964972 -0.42292162 -0.82551045  1.23681731 -0.84011649
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.92964972 -1.16259137 -1.3554047   1.23681731 -1.3873724
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  1.52579886  2.00742183  1.67630487 -1.24428462 -0.01923264
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.40556188 -0.42292162 -0.27656382  0.15807734  0.25439532
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  2.01106538  1.21491853  2.41101217 -0.56108264 -0.84011649
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.52579886  1.34700241  1.65248939 -0.23746065  0.80165122
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.83259642 -0.76633972 -0.90767383 -0.41725065  1.34890713
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.69672179  0.29033135 -0.21107128  0.05020334  0.52802327
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  1.21522829  1.21491853  1.31550047 -0.56108264 -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.91994439 -0.37008807 -0.84218128 -0.02171266 -0.84011649
   2.21487254 -0.51195388 -1.28551249]
 [-0.8576193  -0.40556188 -0.37008807 -0.35991798  0.15807734  0.80165122
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.059943    0.66016622  0.23427805 -1.28024262 -0.29286059
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.63290847  0.15824746  0.78560622  0.87723732 -0.56648854
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.51232051 -0.37008807 -0.67190066  1.4166073  -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348 -0.11440197  0.15824746 -0.03245524  0.30190933  1.62253508
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.91994439 -0.73992294 -0.98626489 -0.30937665  1.07527918
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  1.52579886  1.61117018  1.47268258 -1.28024262 -1.3873724
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.35703523 -0.31725452 -0.41945666 -0.41725065  1.34890713
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.51232051 -0.42292162 -0.3003793  -0.05767066  0.52802327
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.38056988 -0.1059203  -0.06936922  0.15807734 -0.29286059
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.07935367  1.21491853  0.83323716 -1.46003262 -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348 -0.35703523  0.47524878 -0.19678199 -0.74087264 -0.84011649
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.70642712 -0.79275649 -0.40159505  0.98511131  1.34890713
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.69672179 -0.73992294 -0.54925098  0.87723732 -1.11374445
   2.21487254 -0.51195388 -1.28551249]
 [-0.8576193  -1.10434567 -0.97767393 -1.20179491 -0.02171266 -0.56648854
   2.21487254 -0.51195388 -1.28551249]
 [ 0.32752348  0.37086455  0.15824746  0.07947748 -0.20150265 -0.29286059
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.5705525  -0.37008807 -0.31109626 -0.02171266  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -1.18198831 -1.03050748 -1.42804189  1.23681731 -1.3873724
  -0.45149325  1.95330095 -1.28551249]
 [ 1.51266626  2.01106538  1.21491853  1.77632985 -1.28024262 -0.84011649
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.21522829  1.21491853  1.45005788 -0.92066263 -0.01923264
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  2.53515322  3.06409289  1.64534475 -2.35898259 -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.52579886  1.61117018  0.85824341 -1.46003262 -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.9878817  -0.97767393 -1.33635232 -0.63299864  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.70642712 -0.76633972 -0.512337    0.69744732  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [ 1.51266626  1.059943    0.95075076  1.39170998 -0.56108264 -0.56648854
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.92964972 -0.68708939 -1.2291827  -0.38129265  0.25439532
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  1.53550419  1.18850175  1.62272006 -0.38129265  0.25439532
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.56084717 -0.52858873 -0.53258015  0.15807734  1.62253508
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.52579886  1.21491853  2.05616164 -0.38129265 -0.56648854
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.089059    1.08283464  1.08091807 -1.10045263  0.25439532
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.38056988 -0.1059203  -0.21821592 -0.20150265 -0.84011649
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.74524844 -0.76633972 -0.86480598 -0.56108264 -0.56648854
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  1.84607476  1.74325406  0.70344284 -1.9994026  -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.10846966  2.53575736  1.67154177 -0.20150265 -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.51232051 -0.84559005 -0.67190066  1.23681731 -1.3873724
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.92964972 -0.68708939 -0.93387085  0.08616134  1.07527918
   2.21487254 -0.51195388 -1.28551249]
 [ 0.32752348 -0.46379386 -0.73992294  0.22356108  1.4525653   1.34890713
   2.21487254 -0.51195388 -1.28551249]
 [ 0.32752348  0.06999931 -0.42292162  0.10448373  0.55361533  1.34890713
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.55526583  0.02616358  0.45338039 -0.38129265 -0.01923264
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.9878817  -1.3475088  -1.40184487  0.69744732 -0.29286059
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.68701646 -0.47575517 -0.88862145  0.33786733 -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.05058865 -0.23800419 -0.16582188 -0.02171266 -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.99758703 -0.76633972 -1.02913273 -0.02171266 -0.56648854
   2.21487254 -0.51195388 -1.28551249]
 [-0.8576193  -1.00729236 -0.87200682 -1.16964402 -0.23746065  0.52802327
   2.21487254 -0.51195388 -1.28551249]
 [ 1.51266626  2.29251996  2.4829238   1.6298647  -1.9994026  -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.93935505 -0.92484038 -0.93268007  0.87723732 -1.11374445
   2.21487254 -0.51195388 -1.28551249]
 [ 0.32752348  0.55526583  0.02616358  1.10116122  1.05702731 -0.29286059
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  2.39927859  2.93200901  1.59533226 -2.53877259 -1.66100035
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.78406976 -0.42292162 -0.39564118  1.09298531  1.62253508
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.80348042 -0.4493384  -0.35753643  0.69744732 -1.66100035
   2.21487254 -0.51195388 -1.28551249]
 [-0.8576193  -1.04611368 -1.03050748 -1.02675119  1.30873331  1.07527918
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.9878817  -1.16259137 -1.395891    0.30190933  0.52802327
  -0.45149325  1.95330095 -1.28551249]
 [-0.8576193  -0.91994439 -0.95125715 -0.97316638  0.33786733  0.52802327
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.059943    0.66016622  0.89634816 -0.77683064  0.80165122
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.21522829  1.08283464  1.3905192  -0.66895664  0.25439532
  -0.45149325 -0.51195388  0.77789987]
 [ 0.32752348  0.05058865 -0.23800419 -0.08127696  0.15807734 -0.84011649
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.53550419  1.29416886  1.3774207  -0.92066263 -1.11374445
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.9878817  -0.8984236  -1.21132109  1.77618729 -1.3873724
  -0.45149325 -0.51195388  0.77789987]
 [ 1.51266626  1.089059    1.08283464  0.53911609 -0.84874664  0.52802327
  -0.45149325 -0.51195388  0.77789987]
 [-0.8576193  -0.91994439 -0.95125715 -1.10415147  1.05702731  0.25439532
  -0.45149325  1.95330095 -1.28551249]]

In [8]:
#Importing and fitting the model on training set
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [9]:
#Fitting the model on training data :
reg.fit(X_train, y_train)

LinearRegression()

In [10]:
#Checking the coefficient(slope) and intercepts.
m = reg.coef_
c = reg.intercept_
m,c

(array([-5.38846861e-01,  2.23382388e+00, -4.71572635e-01, -5.88046427e+00,
         3.58440015e-01,  2.80530384e+00, -4.22214075e+13, -4.56657523e+13,
        -5.45590007e+13]),
 23.48169428373807)

In [11]:
#Predicting the target: mpg against the predictors in the training data set
#Predicted data stored in y_pred_train
y_pred_train = reg.predict(X_train)
y_pred_train

array([31.4588055 , 21.66372944, 28.94497944, 22.80435444, 25.419743  ,
       10.42154194, 23.39029194, 26.1463055 , 29.9431805 , 32.841618  ,
       25.3181805 , 24.37466694, 12.39810444, 26.841618  , 20.42935444,
       28.60904194, 23.8181805 , 35.7713055 , 23.591618  , 31.216618  ,
       31.5838055 ,  8.99966694, 28.232243  , 22.810368  , 24.86685444,
       30.67935444, 26.20279194, 25.872868  , 20.31997944, 35.685368  ,
       12.58560444, 16.20279194, 32.747868  , 27.04654194, 20.88247944,
       29.54654194, 23.466618  , 27.26529194, 22.64810444, 28.55435444,
       16.51529194, 26.732243  , 34.1150555 , 10.27310444, 20.96060444,
       17.42154194, 14.74966694, 29.654118  , 27.19497944, 32.82779194,
       31.747868  , 20.92154194, 22.45279194, 24.982243  , 23.15591694,
       14.23404194, 26.18716694,  9.21060444, 27.3025555 , 16.02310444,
       24.46841694, 29.372868  , 27.98404194, 17.99966694, 29.919743  ,
       22.51529194, 26.10122944, 11.67935444, 25.47622944, 19.77310444,
       13.39029194, 30.81216694, 22.310368  , 17.16372944, 15.94497944,
       35.0681805 , 17.31997944, 18.91372944, 19.53872944, 15.85122944,
       21.89810444, 29.513493  , 20.05435444, 28.58560444, 27.92935444,
       27.888493  , 24.47622944, 17.58560444, 33.591618  , 21.25747944,
       23.99185444, 11.39029194, 10.51529194, 32.14810444, 24.38247944,
       32.1619305 , 25.294743  , 22.71841694, 32.1306805 , 25.904118  ,
       34.654118  , 34.044743  ,  8.39029194, 15.43716694, 30.5681805 ,
       12.28872944, 20.42935444, 27.48404194, 16.79654194, 13.03872944,
       16.71060444, 25.419743  , 28.7244305 , 26.372868  , 20.58560444,
       17.66372944, 21.99966694, 20.66372944, 20.28091694, 20.39029194,
       19.68716694, 19.56216694, 30.216618  , 10.48404194, 24.42935444,
       23.88247944, 29.1619305 , 27.825993  , 11.84341694, 24.529118  ,
       23.43716694, 22.73404194, 29.5994305 , 28.87466694, 13.67154194,
       19.79654194, 29.497868  , 18.19497944, 35.091618  , 26.6931805 ,
       18.08560444, 10.13247944, 17.17154194, 26.529118  , 21.28091694,
       30.85122944, 24.138493  , 29.747868  , 15.51529194, 24.0525555 ,
       28.86685444, 26.450993  , 28.779118  , 11.78872944, 20.72622944,
       19.37466694, 17.53872944, 20.857243  , 25.513493  , 32.8338055 ,
       22.888493  , 29.24185444, 27.513493  , 31.4275555 , 30.50747944,
       15.06216694, 19.83560444, 23.1619305 , 11.74185444, 28.31216694,
       10.46060444, 25.72622944, 19.89029194, 28.00747944, 12.24185444,
       28.96841694, 31.763493  , 28.091618  , 21.03091694, 29.50747944,
       15.28091694, 30.41372944, 22.29654194, 21.466618  , 29.075993  ,
       24.232243  , 35.3806805 , 30.8338055 , 24.73404194, 30.09341694,
       25.232243  , 20.40591694, 14.19497944, 26.700993  , 14.89029194,
       29.872868  , 17.21841694, 34.029118  , 26.982243  ,  6.67154194,
       24.96841694, 26.357243  , 18.279118  , 27.53872944, 33.279118  ,
       32.497868  , 16.46841694, 15.20279194, 11.92154194, 20.92935444,
       23.89810444, 16.80435444, 23.950993  ,  5.86685444, 15.10122944,
       31.388493  , 30.435368  , 21.21841694, 35.0369305 , 24.825993  ,
       21.90591694,  9.17154194, 23.83560444, 15.64810444, 34.716618  ,
       24.935368  , 11.53872944, 25.67935444, 22.92935444, 22.794743  ,
       25.28872944, 16.74185444, 26.075993  , 29.0994305 , 27.357243  ,
       16.65591694, 33.060368  , 29.17935444, 23.01529194, 29.3650555 ,
       13.73404194, 23.497868  , 35.435368  , 23.89810444, 12.12466694,
       23.77310444, 28.06997944, 22.216618  , 33.044743  , 24.28872944,
       26.33560444, 23.76529194, 31.85904194,  8.68716694, 10.81216694,
       24.013493  , 34.3025555 , 10.53872944, 29.060368  , 35.888493  ,
       24.01529194, 19.98404194,  6.49185444, 26.56997944, 20.39029194,
       19.48404194, 32.357243  , 30.404118  , 24.8025555 , 21.47622944,
       29.310368  , 14.68716694, 30.42154194, 19.25747944, 27.279118  ,
       25.5369305 , 19.85904194, 29.16372944, 23.247868  , 21.29654194,
       29.61685444, 28.66372944, 18.64810444, 31.03091694, 12.42935444,
       28.3338055 , 12.73404194, 31.825993  ,  7.67154194, 28.435368  ,
       27.06216694, 33.7088055 , 21.14810444, 35.185368  , 12.17935444,
       28.74185444, 23.85904194, 15.54654194, 24.154118  , 13.76529194,
       32.6619305 , 33.138493  , 31.1775555 , 16.59341694, 13.28091694,
       24.14029194, 30.716618  , 23.24185444, 33.997868  , 22.87466694,
       27.529118  , 18.67154194, 21.00747944])

In [12]:
# Prediction Accuracy in terms of how close is the predicted value of target: mpg
# to the real value in training data set
from sklearn.metrics import r2_score
r2_S = r2_score(y_train, y_pred_train)
r2_S

0.8191544354390766

In [13]:
# Predicting the target: mpg against the predictors in the testing data set
# Predicted data stored in y_pred_test
y_pred_test = reg.predict(X_test)

In [14]:
# Prediction Accuracy in terms of how close the predicted value of target: mpg
# to the real value in testing data set
r2_S = r2_score(y_test, y_pred_test)
r2_S

0.8387624072149144